apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speider
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspeider
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-speider-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
  observability:
    logging:
      destinations:
        - id: elastic
